# Generated by Django 4.1.7 on 2023-03-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
