# Generated by Django 4.1.7 on 2023-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0002_alter_painting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(),
        ),
    ]
