# Generated by Django 4.1.4 on 2023-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0003_alter_painting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
