# Generated by Django 4.1.4 on 2023-05-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0006_alter_userlikepainting_painting_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlikepainting',
            old_name='painting_id',
            new_name='painting',
        ),
        migrations.RenameField(
            model_name='userlikepainting',
            old_name='user_id',
            new_name='user',
        ),
    ]
